"""Adicionar campos de atividades aos dias da semana

Revision ID: 136b149cf1c7
Revises: 
Create Date: 2026-06-11 19:44:02.567217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136b149cf1c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday_activities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tuesday_activities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wednesday_activities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('thursday_activities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('friday_activities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_attendance', schema=None) as batch_op:
        batch_op.drop_column('friday_activities')
        batch_op.drop_column('thursday_activities')
        batch_op.drop_column('wednesday_activities')
        batch_op.drop_column('tuesday_activities')
        batch_op.drop_column('monday_activities')

    # ### end Alembic commands ###
